version: "3.8"
services:
    steam-extractor:
        image: steam-extractor
        build:
            context: .
            dockerfile: Dockerfile
        container_name: steam-extractor
        ports: 
            - "4000:4000"
        volumes:
            - .:/usr/steam-extractor
            - /usr/steam-extractor/node_modules
        environment: 
            - CHOKIDAR_USEPOLLING=true